"var-model-temp.ttf":
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
