PlaywriteAT[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
PlaywriteAT-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
PlaywriteGBJoined[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
PlaywriteGBJoined-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
PlaywriteGBSemiJoin[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
PlaywriteGBSemiJoin-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100.0
    - name: ExtraLight
      value: 200.0
    - name: Light
      value: 300.0
    - name: Regular
      value: 400.0
      flags: 2
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
